// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlxqvmmzeumuddvcyjob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseHF2bW16ZXVtdWRkdmN5am9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMTc5MjgsImV4cCI6MjA1Njg5MzkyOH0.u08nAKqBcLnGQzHq7GSidV8GrnAxlwIljjb9h1O333I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);